### ISSUE TITLE
Stalling at Step6

### ISSUE THREAD

**Issue by hpf0815** [HKU-BAL/ClairS-TO#15]
Hi, I had to reinstall ClairS-TO and did at first not notice that there was an update last week. Whenever I ran my pipeline it stalled at step 6, when writing logs I think. After downgrading to version 0.1.0 it runs again through as before. Does someone else see this issue?

**Comment by aquaskyline** [comment]
Hi Hans-Peter,

Could you please send me the log file?

**Comment by hpf0815** [comment]
Hi, sorry for my late reply, I was on holiday. I moved the clairs-to log file to the logs folder and bundled it in a tar file so you have all logs available.
[clairs-to_logs.tar.gz](https://github.com/user-attachments/files/16450903/clairs-to_logs.tar.gz)

**Comment by JasonCLEI** [comment]
Hi, @hpf0815,

Thanks a lot for your interest and support. We have checked your running logs and found that the issue was caused by the incompatibility in your data and the Verdict module at the moment. It is worth noting that the Verdict module currently only works for GRCh38 reference genome and we are still continuing to improve it. We have released a new Docker image with adding more compatibility checks in the Verdict module. You could rerun the program with your data with the latest image of ClairS-TO and check if the same issue still exists.

Lei
