### ISSUE TITLE
IndexError in STEP5

### ISSUE THREAD

**Issue by naziafrin** [HKU-BAL/ClairS-TO#6]
I am getting the following IndexError in STEP 5 while running ClairS_TO with the latest docker image and I am using PacBio Hifi data (haplotagged.bam file) as the input.

Traceback (most recent call last):
  File "/opt/bin/clairs_to.py", line 107, in <module>
    main()
  File "/opt/bin/clairs_to.py", line 101, in main
    submodule.main()
  File "/opt/bin/src/postprocess_vcf.py", line 231, in main
    merge_vcf(args)
  File "/opt/bin/src/postprocess_vcf.py", line 99, in merge_vcf
    qual = float(columns[5])
IndexError: list index out of range

Even with the error, the final output file output.vcf.gz is generated but I am concerned about the output. Could you please help me with that?

**Comment by JasonCLEI** [comment]
Hi, @naziafrin,

Thanks a lot for your interest. It seems that the error was caused by the wrong file of `/tmp/vcf_output/pileup_filtering.vcf` in the vcf post-processing step. Could you please provide your running log of `run_clairs_to.log` file and `/tmp/vcf_output/pileup_filtering.vcf` file with me (if possible, send them to my email address [lchen@cs.hku.hk](mailto:lchen@cs.hku.hk)), and I will check the issue for you.

Lei
